apiVersion: v1
kind: ReplicationController
metadata:
  name: mynginx-rc
spec:
  replicas: 2
  selector:
    app: mynginxpods
  template:
    metadata:
      labels:
        app: mynginxpods
    spec:
      containers:
        - name: mycontainer
          image: nginx
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mynginx-svc
  labels:
    app: mynginxpods
spec:
  type: NodePort
  ports: 
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: mynginxpods
